### ISSUE TITLE
How to set environment variable?

### ISSUE THREAD

**Issue by cmarqu** [krupan/albion#1]
Hi,

it would be nice if there was an example on how to set an environment variable.
I figured since you are eval'ing the output, I should write something like 
`echo export AMSHOME=/tools/cds/incisive_15.20.007_Linux;` (with the semicolon for separating multiple lines), but it doesn't seem to work for me. It may be that this is because my `$SHELL` is set to tcsh, and I explicitly started `bash --login`?

**Comment by cmarqu** [comment]
Oh, I see. albion is just source'ing whatever it finds in the config file and that's it.
I was somehow thrown off by the shell function in the `mypath` example and assumed I would also need to have a shell function with the name of my config.
Maybe it would be good to provide a simple example called `env-vars`?

**Comment by krupan** [comment]
A simple example is a great suggestion.  I keep getting good ideas from
people right when I'm starting a vacation (am I vacationing too much?), but
I will add that example when I return home.

Bryan

**Comment by cmarqu** [comment]
I would have made a pull request here, but wasn't sure whether your gateway to hg is bidirectional, so may have been wasted effort...

**Comment by krupan** [comment]
Don't hesitate to create a pull request.  I'm sure I can figure out how to get into my repo.

**Comment by krupan** [comment]
I added an example in commit cb88287fb659047422597a6562d581ebb0f66b9c
